services:
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:8.0
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}  # Corrigido de ${DB_NAME} para ${DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./docker/mysql/data:/docker-entrypoint-initdb.d:rw

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "7070:80"
    volumes:
      - /sessions
    logging:
      driver: none
    links:
      - mysql

  web:
    container_name: ${APP_NAME}-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.local
    environment:
      XDEBUG_CONFIG: remote_host=172.20.0.4
      PHP_XDEBUG_ENABLED: 1
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PORT: ${DB_PORT}
      TOKEN: ${TOKEN}
    links:
      - mysql
    volumes:
      - ./src:/var/www/html

  nginx:
    depends_on:
      - web
    container_name: ${APP_NAME}-nginx
    hostname: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.local
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    links:
      - web