name: Awake Staging Environment ⬆️

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  awake-env:
    name: Autoscaling Group Awake
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        
    - name: Get Auto Scaling Group Name
      id: get-asg
      run: |
        env=$(aws autoscaling describe-auto-scaling-groups \
         --query "AutoScalingGroups[?contains(Tags[?Key=='elasticbeanstalk:environment-name'].Value, 'prisma-${{ github.ref_name }}-env')].AutoScalingGroupName" \
         --output text)
        if [ -z "$env" ]; then
          echo "No Auto Scaling Group found for the staging environment"
          exit 1
        fi
        echo "Staging Env: $env"
        echo "::set-output name=env::$env"

    - name: Update Auto Scaling Group
      run: |
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name ${{ steps.get-asg.outputs.env }} \
          --min-size 1 \
          --max-size 1